# Generated by Django 6.1 on 2026-08-29 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('food', 'Comida y restaurantes'), ('groceries', 'Supermercado'), ('transportation', 'Transporte'), ('shopping', 'Compras'), ('housing', 'Vivienda'), ('bills', 'Servicios y facturas'), ('health', 'Salud'), ('entertainment', 'Entretenimiento'), ('travel', 'Viajes'), ('education', 'Educación'), ('personal', 'Personal'), ('subscriptions', 'Suscripciones'), ('other', 'Otros')], default='other', max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_method', models.CharField(choices=[('voice', 'Voz'), ('text', 'Texto'), ('receipt', 'Recibo')], default='text', max_length=10)),
                ('raw_input', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
